// Auto-generated file from subreddits.txt
// Do not edit this file directly - edit subreddits.txt instead
// Run 'npm run generate-subreddits' to regenerate this file
// Generated at: 2025-10-14T21:37:28.375Z

export const IMAGE_SUBREDDITS: string[] = [
  'maplestory',
  'okbuddyretard',
  'meirl',
  'okbuddyphd',
  'memeeconomy',
  'wallstreetbets',
  'aww',
  'pics',
  'funny',
  'mildlyinteresting',
  'cats',
  'dogs',
  'earthporn',
  'mademesmile',
  'eyebleach',
  'cozyplaces',
  'foodporn',
  'itookapicture',
  'photoshopbattles',
  'oldschoolcool',
  'wholesomememes',
  'animalsbeingderps',
  'oddlysatisfying',
  'interestingasfuck',
  'nextfuckinglevel',
  'damnthatsinteresting',
  'beamazed',
  'toptalent',
  'blackmagicfuckery',
  'perfecttiming',
  'satisfying',
  'mildlyinfuriating'
];

export const SUBREDDIT_COUNT = 32;
